# remote git
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/skymarlio82/spring-cloud-full
          searchPaths: respo
          username: skymarlio82
          password: _Rrf9jxwd
      label: master
# ---native
#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
  profiles:
    active: native
  application:
    name: config-server
server:
  port: 8769
management:
  security:
    enabled: false