# remote git
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/skymarlio82/spring-cloud-full
          searchPaths: respo
          username: skymarlio82
          password: _Rrf9jxwd
      label: master
# ---native
#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
  profiles:
    active: git
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8769
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"